# To run all pre-commit checks, use:
#
#     pre-commit run -a
#
# To install pre-commit hooks that run every time you commit:
#
#     pre-commit install
#

ci:
  autoupdate_commit_msg: "⬆️🪝 update pre-commit hooks"
  autofix_commit_msg: "🎨 pre-commit fixes"
  skip: [mypy]

repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  # Handling unwanted unicode characters
  - repo: https://github.com/sirosen/texthooks
    rev: "0.6.3"
    hooks:
      - id: fix-ligatures
      - id: fix-smartquotes

  # Clean jupyter notebooks
  - repo: https://github.com/srstevenson/nb-clean
    rev: "3.1.0"
    hooks:
      - id: nb-clean

  # Check for spelling
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.6"
    hooks:
      - id: codespell
        args: [""]
        exclude: ""
        types: [python, text, markdown]

  # Format configuration files with prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, javascript, json]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
        types_or: [python, pyi, jupyter]
        exclude: "^src/qutip_qoc/[^/]*\\.ipynb"
      - id: ruff-format
        types_or: [python, pyi, jupyter]
        exclude: "^src/qutip_qoc/[^/]*\\.ipynb"

  # Also run Black on examples in the documentation
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==23.*]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        files: ^(src|tests)
        exclude: "^src/qutip_qoc/[^/]*\\.ipynb"
        args: []
        additional_dependencies:
          - qutip
          - qutip-qip
          - qutip-qtrl
          - numpy
          - scipy
          - jax
          - jaxlib
          - diffrax
          - pytest
          - gymnasium
          - stable-baselines3
