name: rtd-environment
channels:
  - conda-forge
dependencies:
  - numpy>=1.16.6,<2.0
  - scipy>=1.10.1
  - cython>=0.29.33
  - sphinx==6.1.3
  - sphinx_rtd_theme==1.2.0
  - sphinxcontrib-bibtex==2.5.0
  - numpydoc==1.5.0
  - matplotlib>=3.6.1
  - docutils==0.18.1
  - sphinxcontrib-bibtex==2.5.0
  - wheel==0.38.4
  - pip
  - pip:
      - jax==0.4.28
      - jaxlib==0.4.28
      - qutip>=5.0.1
      - ..[full]
